config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: "auth/omniauth_callbacks", registrations: "auth/registrations" , sessions: 'auth/sessions'}, path: "", path_names: { 
    sign_in: 'login', 
    sign_out: 'logout', 
    registration: 'register',
    sign_up: 'new' }

  devise_scope :user do
    get "register", to: "devise/registrations#new"
    get "logout",   to: "devise/sessions#destroy"
  end
  get 'remote_sign_up' => 'remote_content#remote_sign_up'

  authenticated :user do
    root to: 'home#authenticated', as: :authenticated_root
  end

  root 'high_voltage/pages#show', id: 'home'

  get 'example' => 'example#index', as: :example

end

app/models/hash_id.rb
# Abstract Class to use encrypted parameters
class HashId < ActiveRecord::Base
  self.abstract_class = true
  
  def to_param
    Hashids.new( self.class.name, 8 ).encrypt( id )
  end

  def self.find_by_param( input )
    find( Hashids.new( self.name, 8 ).decrypt( input ) ).first
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, omniauth_providers: [:facebook]

  enum status: %i(common admin)

  def status_enum
    User.statuses
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  rails_admin do
  	# Change visibility
  	# https://github.com/sferik/rails_admin/wiki/Navigation
  	#
    # visible false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :layout_by_resource
  before_filter :configure_permitted_parameters, if: :devise_controller?
  #before_action :set_locale
  #rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def after_sign_up_path_for(resource)
    root_url # After login, it goes to this
  end


  def after_sign_in_path_for(resource)
    root_url # After register, it goes to this
  end

  def append_info_to_payload(payload)
    super
    payload[:host] = request.host
  end

  protected

  def layout_by_resource
    if devise_controller?
      "login/application"
    else
      "application"
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email) }
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :name, :email, :password, :password_confirmation, :current_password) }
  end

  def set_locale
    I18n.locale = extract_locale_from_accept_language_header
    # if params[:lang] is nil then I18n.default_locale
    I18n.locale = params[:locale] if params[:locale].present?
  end

  def extract_locale_from_accept_language_header
    request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  end

  private

  def user_not_authorized
    flash[:error] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/example_controller.rb
# This is an example controller that uses the Authenticated
class ExampleController < AuthenticatedController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home/application'
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 # POST /resource
  def create
    build_resource(sign_up_params)

    if resource.save
      respond_to do |format|
        format.html {
          yield resource if block_given?
          if resource.active_for_authentication?
            set_flash_message :notice, :signed_up if is_flashing_format?
            sign_up(resource_name, resource)
            respond_with resource, :location => after_sign_up_path_for(resource)
          else
            set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
            expire_data_after_sign_in!
            respond_with resource, :location => after_inactive_sign_up_path_for(resource)
          end
        }
        format.js {
          flash[:notice] = "Account created."
          render :template => "remote_content/devise_success_sign_up.js.erb"
          flash.discard
          sign_up(resource_name, resource)
        }
      end
    else
      respond_to do |format|
        format.html {
          clean_up_passwords resource
          respond_with resource
        }
        format.js {
          flash[:alert] = @user.errors.full_messages.to_sentence
          render :template => "remote_content/devise_errors.js.erb"
          flash.discard
        }
      end
    end
  end

end

app/controllers/remote_content_controller.rb
class RemoteContentController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  #protected

  # CUSTOM (Mix of actual devise controller method and ajax customization from http://natashatherobot.com/devise-rails-sign-in/):
  def create
    # (NOTE: If user is not confirmed, execution will never get this far...)
    respond_to do |format|
      format.html { super }                     
      format.js  do
        resource = warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#failure")
        return sign_in_and_redirect(resource_name, resource)
      end          
    end

  end

  def sign_in_and_redirect(resource_or_scope, resource=nil)
    scope = Devise::Mapping.find_scope!(resource_or_scope)
    resource ||= resource_or_scope
    sign_in(scope, resource) unless warden.user(scope) == resource
    respond_to do |format|
      format.json {render :json => {:success => true, :redirect => stored_location_for(scope) || after_sign_in_path_for(resource)}}
      format.html {redirect_to root_url}
    end
  end

  def failure
    respond_to do |format|
      format.json { render:json => {:success => false, :errors => ["Login failed."]} }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
   :user
  end

  def resource
   @resource ||= User.new
  end

  def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
  end

  def flash_normal
    render "layouts/flashes"
  end

  def flash_form
    render "layouts/form_flashes"
  end

  def twitterized_type(type)
    case type
      when :errors
        "alert-error"
      when :alert
        "alert-warning"
      when :error
        "alert-error"
      when :notice
        "alert-success"
      else
        "alert-info"
    end
  end
end

app/helpers/example_helper.rb
module ExampleHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/example/index.html.haml
Protected by Password

app/views/home/authenticated.html.haml
You are authenticated

app/views/home/index.en.html.haml
/
  Carousel
  \==================================================
#myCarousel.carousel.slide{"data-ride" => "carousel"}
  / Indicators
  %ol.carousel-indicators
    %li.active{"data-slide-to" => "0", "data-target" => "#myCarousel"}
    %li{"data-slide-to" => "1", "data-target" => "#myCarousel"}
    %li{"data-slide-to" => "2", "data-target" => "#myCarousel"}
  .carousel-inner
    .item.active
      %img{:alt => "First slide", :src => "data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="}
        .container
          .carousel-caption
            %h1 Example headline.
            %p
              Note: If you're viewing this page via a
              %code file://
              URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.
            %p
              %a.btn.btn-lg.btn-primary{:href => "#", :role => "button"} Sign up today
    .item
      %img{:alt => "Second slide", :src => "data:image/gif;base64,R0lGODlhAQABAIAAAGZmZgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="}
        .container
          .carousel-caption
            %h1 Another example headline.
            %p Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
            %p
              %a.btn.btn-lg.btn-primary{:href => "#", :role => "button"} Learn more
    .item
      %img{:alt => "Third slide", :src => "data:image/gif;base64,R0lGODlhAQABAIAAAFVVVQAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="}
        .container
          .carousel-caption
            %h1 One more for good measure.
            %p Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
            %p
              %a.btn.btn-lg.btn-primary{:href => "#", :role => "button"} Browse gallery
  %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel", :role => "button"}
    %span.glyphicon.glyphicon-chevron-left
  %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel", :role => "button"}
    %span.glyphicon.glyphicon-chevron-right
/ /.carousel
/
  Marketing messaging and featurettes
  \==================================================
/ Wrap the rest of the page in another container to center all the content.
.container.marketing
  / Three columns of text below the carousel
  .row
    .col-lg-4
      %img.img-circle{:alt => "Generic placeholder image", :src => "data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==", :style => "width: 140px; height: 140px;"}
        %h2 Heading
        %p Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.
        %p
          %a.btn.btn-default{:href => "#", :role => "button"} View details &raquo;
    / /.col-lg-4
    .col-lg-4
      %img.img-circle{:alt => "Generic placeholder image", :src => "data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==", :style => "width: 140px; height: 140px;"}
        %h2 Heading
        %p Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.
        %p
          %a.btn.btn-default{:href => "#", :role => "button"} View details &raquo;
    / /.col-lg-4
    .col-lg-4
      %img.img-circle{:alt => "Generic placeholder image", :src => "data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==", :style => "width: 140px; height: 140px;"}
        %h2 Heading
        %p Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
        %p
          %a.btn.btn-default{:href => "#", :role => "button"} View details &raquo;
    / /.col-lg-4
  / /.row
  / START THE FEATURETTES
  %hr.featurette-divider
    .row.featurette
      .col-md-7
        %h2.featurette-heading
          First featurette heading.
          %span.text-muted It'll blow your mind.
        %p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
      .col-md-5
        %img.featurette-image.img-responsive{:alt => "Generic placeholder image", "data-src" => "holder.js/500x500/auto"}
    %hr.featurette-divider
      .row.featurette
        .col-md-5
          %img.featurette-image.img-responsive{:alt => "Generic placeholder image", "data-src" => "holder.js/500x500/auto"}
        .col-md-7
          %h2.featurette-heading
            Oh yeah, it's that good.
            %span.text-muted See for yourself.
          %p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
      %hr.featurette-divider
        .row.featurette
          .col-md-7
            %h2.featurette-heading
              And lastly, this one.
              %span.text-muted Checkmate.
            %p.lead Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.
          .col-md-5
            %img.featurette-image.img-responsive{:alt => "Generic placeholder image", "data-src" => "holder.js/500x500/auto"}
        %hr.featurette-divider
          / /END THE FEATURETTES
          / FOOTER

app/views/layouts/_flashes.html.haml
#flash
  - flash.each do |type, message|
    .alert.alert-dismissable{ :class => twitterized_type(type) }
      %button.close{"data-dismiss" => "alert", "aria-hidden" => "true"} ×
      %p= message

app/views/layouts/_footer.html.haml
%footer
  %p.pull-right
    %a{:href => "#"} Back to top
  %p
    \&copy; 2014 Company, Inc. &middot;
    %a{:href => "#"} Privacy
    \&middot;
    %a{:href => "#"} Terms

app/views/layouts/_form_flashes.html.haml
#form_flashes
  - flash.each do |type, message|
    .alert.alert-dismissable{ :class => twitterized_type(type) }
      %button.close{"data-dismiss" => "alert", "aria-hidden" => "true"} ×
      %p= message

app/views/layouts/_google_analytics.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54881237-1', 'auto');
  ga('send', 'pageview');

app/views/layouts/_header.html.haml
%head
  %meta{:charset => "utf-8"}
  %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
  %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
  %meta{:content => "", :name => "description"}
  %meta{:content => "", :name => "author"}
  %link{:href => "../../favicon.ico", :rel => "icon"}
  %title Generic Rails App

  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  
  / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
  /[if lt IE 9]
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    / Custom styles for this template

app/views/layouts/_login.html.haml
%session.col-md-12.user-fundo
  .container
    .row
      .col-md-12.text-right
        - if current_user.present?
          = link_to edit_user_registration_path do
            - #%i.fa.fa-user
            = current_user.name
          &nbsp;(
          = link_to destroy_user_session_path do
            - #%i.fa.fa-sign-out
            sair
          )

app/views/layouts/_menu.html.haml
%ul.nav.navbar-nav
  %li{ class: "#{current_page?(root_path) ? 'active' : ''}"}
    = link_to 'Home', root_path
  %li{ class: "#{current_page?(page_path('about')) ? 'active' : ''}"}
    = link_to 'About', page_path('about')
  %li{ class: "#{current_page?(page_path('contact')) ? 'active' : ''}"}
    = link_to 'Contact', page_path('contact')
  %li.dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      Dropdown
      %span.caret
    %ul.dropdown-menu{:role => "menu"}
      %li
        %a{:href => "#"} Action
      %li
        %a{:href => "#"} Another action
      %li
        %a{:href => "#"} Something else here
      %li.divider
      %li.dropdown-header Nav header
      %li
        %a{:href => "#"} Separated link
      %li
        %a{:href => "#"} One more separated link

  - if !current_user.present?
    %li
      = link_to "Login", remote_sign_up_path, :remote => true
      - #= link_to new_user_session_path do
      - #  Entrar
    %li
      = link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)
  - else
    %li
      = link_to "Sair", logout_path

app/views/layouts/_notices.html.haml
%session.col-md-12.user-fundo.flashes
  #flash
    - flash.each do |type, message|
      .alert.alert-dismissable{ :class => twitterized_type(type) }
        %button.close{"data-dismiss" => "alert", "aria-hidden" => "true"} ×
        %p= message

app/views/layouts/application.html.haml
!!!
%html
  = render 'layouts/header'
  %body
  .navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
    .container
      .navbar-header
        %button.navbar-toggle.collapsed{ type:'button', data:{toggle: 'collapse', target: '#navbar'}, aria:{ expanded: 'false', controls: 'navbar'}}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to root_path, class: 'navbar-brand' do
          Generic Rails
      .collapse.navbar-collapse
        = render 'layouts/menu'

  = render 'layouts/login'
  = render 'layouts/notices'

  .container
    = yield

  = render 'layouts/footer'
  = render 'layouts/google_analytics'

app/views/layouts/home/application.html.haml
!!!
%html
  = render 'layouts/header'
  %body
    .navbar-wrapper
      .container
        .navbar.navbar-inverse.navbar-static-top{:role => "navigation"}
          .container
            .navbar-header
              %button.navbar-toggle.collapsed{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
                %span.sr-only Toggle navigation
                %span.icon-bar
                %span.icon-bar
                %span.icon-bar
              %a.navbar-brand{:href => "#"} Generic Rails
            .navbar-collapse.collapse
              = render 'layouts/menu'
              
        = render 'layouts/notices'

    = yield

    = render 'layouts/footer'

app/views/remote_content/_remote_sign_up.html.haml
#sign_up_modal.modal.fade
  .modal-dialog.modal-sm
    #sign_up_content.modal-content
      .modal-body
        .section-title
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"}
            %i.fa.fa-times-circle
          %img{src: asset_path('minilogo.png'), style: 'padding: 5px;'}

        .tabs-wrapper
          %ul.nav.nav-tabs
            %li#sign_in_button.active
              %a{href: '#sign_in', data:{toggle: 'tab'}}
                Entrar
            %li#sign_up_button
              %a{href: '#sign_up', data:{toggle: 'tab'}}
                Criar sua conta
          .tab-content
            #sign_up.tab-pane.fade
              = simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :remote => true, :format => :js,  :html => {:class => "form-signin"}) do |f|
                .modal-body
                  //= f.error_notification
                  = f.input :username, :autofocus => true, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "Usuário"
                  = f.input :name, :autofocus => true, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "Nome completo"
                  = f.input :email, :autofocus => true, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "E-mail"
                  = f.input :password, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "Senha"
                  = f.input :password_confirmation, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "Confirmar senha"
                  = link_to "Esqueceu a senha?", new_user_password_path
                .modal-footer
                  .form-actions
                    %a{ :href => "#", :class => "btn btn-sm", "data-dismiss" => "modal" } Cancelar
                    = f.button :submit, "Criar conta", :class => "btn btn-success"

            #sign_in.tab-pane.fade.active.in
              = simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), :remote => true, :format => :js,  :html => {:class => "form-signin sign_in_user"}) do |f|
                .modal-body
                  //= f.error_notification
                  = f.input :email, :autofocus => true, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "E-mail"
                  = f.input :password, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "Senha"
                  = f.input :remember_me, label: 'Lembre-me', as: :boolean if devise_mapping.rememberable?
                  
                  = link_to "Esqueceu a senha?", new_user_password_path
                .modal-footer
                  .form-actions
                    %a{ :href => "#", :class => "btn btn-sm", "data-dismiss" => "modal" } Cancelar
                    = f.button :submit, "Entrar", :class => "btn btn-success"
      :javascript

        $("form.sign_in_user").bind("ajax:error", function(e, data, status, xhr){
          if(data.success){
            if( data.status == 200 ) {
              $('.modal').modal('hide');

              if($('#flash').length > 0) {
                $('#flash').remove();
                $('.flashes').append( "<div id=\'flash\'>\n<div class=\'alert alert-dismissable alert-success\'>\n<button aria-hidden=\'true\' class=\'close\' data-dismiss=\'alert\'>×<\/button>\n<p>Entrou com sucesso... Aguarde, redirecionando...<\/p>\n<\/div>\n<\/div>\n" );
              }
              else {
                
                $('.flashes').append( "<div id=\'flash\'>\n<div class=\'alert alert-dismissable alert-success\'>\n<button aria-hidden=\'true\' class=\'close\' data-dismiss=\'alert\'>×<\/button>\n<p>Entrou com sucesso... Aguarde, redirecionando...<\/p>\n<\/div>\n<\/div>\n" );
              }
              $('#loading').show();
              if (typeof login_action == 'function') login_action(null, null, JSON.parse(data.responseText).redirect);

            } else {
              if($('#flash').length > 0) $('#flash').remove();
              $('.modal-body').prepend( "<div id=\'flash\'>\n<div class=\'alert alert-dismissable alert-danger\'>\n<button aria-hidden=\'true\' class=\'close\' data-dismiss=\'alert\'>×<\/button>\n<p>" + data.responseText + "<\/p>\n<\/div>\n<\/div>\n" );
            }
          }
        });

app/views/remote_content/_remote_sign_up.pt.html.haml
#sign_up_modal.modal.fade
  .modal-dialog.modal-sm
    #sign_up_content.modal-content
      .modal-body
        .section-title
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"}
            %i.fa.fa-times-circle
          %img{src: asset_path('minilogo.png'), style: 'padding: 5px;'}

        .tabs-wrapper
          %ul.nav.nav-tabs
            %li#sign_in_button.active
              %a{href: '#sign_in', data:{toggle: 'tab'}}
                Login
            %li#sign_up_button
              %a{href: '#sign_up', data:{toggle: 'tab'}}
                Register
          .tab-content
            #sign_up.tab-pane.fade
              = simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :remote => true, :format => :js,  :html => {:class => "form-signin"}) do |f|
                .modal-body
                  //= f.error_notification
                  = f.input :username, :autofocus => true, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "Username"
                  = f.input :name, :autofocus => true, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "Name"
                  = f.input :email, :autofocus => true, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "E-mail"
                  = f.input :password, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "Password"
                  = f.input :password_confirmation, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "Confirm password"
                  = link_to "Forgot your password?", new_user_password_path
                .modal-footer
                  .form-actions
                    %a{ :href => "#", :class => "btn btn-sm", "data-dismiss" => "modal" } Cancelar
                    = f.button :submit, "Criar conta", :class => "btn btn-success"

            #sign_in.tab-pane.fade.active.in
              = simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), :remote => true, :format => :js,  :html => {:class => "form-signin sign_in_user"}) do |f|
                .modal-body
                  //= f.error_notification
                  = f.input :email, :autofocus => true, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "E-mail"
                  = f.input :password, :label => false, :input_html => {:class => 'form-control'}, :placeholder => "Password"
                  = f.input :remember_me, label: 'Remember me', as: :boolean if devise_mapping.rememberable?
                  
                  = link_to "Forgot your password?", new_user_password_path
                .modal-footer
                  .form-actions
                    %a{ :href => "#", :class => "btn btn-sm", "data-dismiss" => "modal" } Cancel
                    = f.button :submit, "Login", :class => "btn btn-success"
      :javascript

        $("form.sign_in_user").bind("ajax:error", function(e, data, status, xhr){
          if(data.success){
            if( data.status == 200 ) {
              $('.modal').modal('hide');

              if($('#flash').length > 0) {
                $('#flash').remove();
                $('.flashes').append( "<div id=\'flash\'>\n<div class=\'alert alert-dismissable alert-success\'>\n<button aria-hidden=\'true\' class=\'close\' data-dismiss=\'alert\'>×<\/button>\n<p>Logged in... Wait, redirecting...<\/p>\n<\/div>\n<\/div>\n" );
              }
              else {
                
                $('.flashes').append( "<div id=\'flash\'>\n<div class=\'alert alert-dismissable alert-success\'>\n<button aria-hidden=\'true\' class=\'close\' data-dismiss=\'alert\'>×<\/button>\n<p>Logged in... Wait, redirecting...<\/p>\n<\/div>\n<\/div>\n" );
              }
              $('#loading').show();
              if (typeof login_action == 'function') login_action(null, null, JSON.parse(data.responseText).redirect);

            } else {
              if($('#flash').length > 0) $('#flash').remove();
              $('.modal-body').prepend( "<div id=\'flash\'>\n<div class=\'alert alert-dismissable alert-danger\'>\n<button aria-hidden=\'true\' class=\'close\' data-dismiss=\'alert\'>×<\/button>\n<p>" + data.responseText + "<\/p>\n<\/div>\n<\/div>\n" );
            }
          }
        });